image: docker:stable

services:
- docker:18.09-dind

variables:
  DOCKER_HOST: tcp://docker:2375

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - Build & Push image

docker build:
  stage: Build & Push image
  only:
    - master
  script:
    - docker info
    - docker build -t gitlab.ilabt.imec.be:4567/lordezan/postgis_pipelinedb_timescale .
    - docker push gitlab.ilabt.imec.be:4567/lordezan/postgis_pipelinedb_timescale:latest && docker image rm gitlab.ilabt.imec.be:4567/lordezan/postgis_pipelinedb_timescale:latest


